version: '3.2'
services:
  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:11
    volumes:
      - pg_0_data:/bitnami/postgresql
    networks:
      - database
      - db-supervision
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=dbpassword
      - POSTGRESQL_USERNAME=dbuser
      - POSTGRESQL_PASSWORD=dbuserpassword
      - POSTGRESQL_DATABASE=dbdb
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11
    volumes:
      - pg_1_data:/bitnami/postgresql
    networks:
      - database
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=dbpassword
      - POSTGRESQL_USERNAME=dbuser
      - POSTGRESQL_PASSWORD=dbuserpassword
      - POSTGRESQL_DATABASE=dbdb
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
  pg-2:
    image: docker.io/bitnami/postgresql-repmgr:11
    volumes:
      - pg_1_data:/bitnami/postgresql
    networks:
      - database
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=dbpassword
      - POSTGRESQL_USERNAME=dbuser
      - POSTGRESQL_PASSWORD=dbuserpassword
      - POSTGRESQL_DATABASE=dbdb
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2:5432
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      - REPMGR_PORT_NUMBER=5432
volumes:
  pg_0_data:
  pg_1_data:

networks:
  database:
    driver: overlay
    attachable: true
  db-supervision:
    external: true
